title: "Jianyu Chen"
description: "Personal website"
theme: minima
# If using GitHub Pages with a project site, set baseurl like "/my-site"
# If using username as repository name, leave baseurl empty
baseurl: ""    # leave empty for user/organization site
url: "https://VoidTrekker.github.io"